spring:
  application:
    name: pms-transactional

  datasource:
    url: ${DB_URL}
    username: ${DB_USER} 
    password: ${DB_PASS} 


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        jdbc.batch_size: 500 
        order_inserts: true
        order_updates: true
        jdbc.batch_versioned_data: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  devtools:
    restart:
      enabled: false
  kafka:
    admin:
      enabled: false
  
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}

    properties:
      schema:
        registry:
          url: ${SPRING_KAFKA_PROPERTIES_SCHEMA_REGISTRY_URL}
      
server:
  port: ${SERVER_PORT} 

logging:
  level:
    # root: INFO
    com.pms: INFO
    # org.hibernate.SQL: DEBUG
    # org.hibernate.type.descriptor.sql.BasicBinder: TRACE

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

app:
  buffer:
    size: 150000
  outbox:
    target-latency-ms: 200
    min-batch: 10
    max-batch: 500
  batch:
    size: 5000
  flush-interval-ms: 10000
  transactions:
    publishing-topic: ${APP_TRANSACTIONS_PUBLISHING_TOPIC}
    consumer:
      group-id: ${APP_TRANSACTIONS_CONSUMER_GROUP_ID}
  trades:
    consumer:
      listening-topic: ${APP_TRADES_CONSUMER_LISTENING_TOPIC}
      group-id: ${APP_TRADES_CONSUMER_GROUP_ID}

