spring:
  config:
    import: optional:file:.env.properties
  application:
    name: pms-transactional
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?reWriteBatchedInserts=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: ${DB_DDL_AUTO:update}
    show-sql: ${DB_SHOW_SQL:false}
    properties:
      hibernate:
        jdbc.batch_size: ${TRANSACTIONAL_JDBC_BATCH_SIZE:500}
        order_inserts: true
        order_updates: true
        jdbc.batch_versioned_data: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  devtools:
    restart:
      enabled: false
  kafka:
    admin:
      enabled: false

    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}

    properties:
      schema:
        registry:
          url: ${SCHEMA_REGISTRY_URL}

server:
  port: ${TRANSACTIONAL_SERVER_PORT:8084}

logging:
  level:
    # root: INFO
    com.pms: INFO
    # org.hibernate.SQL: DEBUG
    # org.hibernate.type.descriptor.sql.BasicBinder: TRACE

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

app:
  buffer:
    size: ${TRANSACTIONAL_BUFFER_SIZE:50}
  outbox:
    target-latency-ms: ${TRANSACTIONAL_OUTBOX_TARGET_LATENCY_MS:200}
    min-batch: ${TRANSACTIONAL_OUTBOX_BATCH_MIN:200}
    max-batch: ${TRANSACTIONAL_OUTBOX_BATCH_MAX:500}
  batch:
    size: ${TRANSACTIONAL_BATCH_SIZE:5000}
  flush-interval-ms: ${TRANSACTIONAL_FLUSH_INTERVAL_MS:10000}
  transactions:
    publishing-topic: ${TRANSACTIONAL_TRANSACTIONS_PUBLISHING_TOPIC}
    consumer:
      group-id: ${TRANSACTIONAL_TRANSACTIONS_CONSUMER_GROUP_ID}
  trades:
    consumer:
      dlt-topic: ${TRANSACTIONAL_TRADES_CONSUMER_DLT_TOPIC}
      consumer-id: ${TRANSACTIONAL_TRADES_CONSUMER_CONSUMER_ID}
      listening-topic: ${TRANSACTIONAL_TRADES_CONSUMER_LISTENING_TOPIC}
      group-id: ${TRANSACTIONAL_TRADES_CONSUMER_GROUP_ID}

rttm:
  client:
    mode: kafka
    kafka:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
      topics:
        trade-events: ${RTTM_TRADE_TOPIC:rttm.trade.events}
        dlq-events: ${RTTM_DLQ_TOPIC:rttm.dlq.events}
        queue-metrics: ${RTTM_QUEUE_METRIC_TOPIC:rttm.queue.metrics}
        error-events: ${RTTM_ERROR_TOPIC:rttm.error.events}
    send-timeout-ms: ${RTTM_SEND_TIMEOUT_MS:3000}
    retry:
      max-attempts: ${RTTM_RETRY_MAX_ATTEMPTS:3}
      backoff-ms: ${RTTM_RETRY_BACKOFF_MS:100}
