name: CI pipeline

on:
  push:
    branches: ["main"]
  
env:
  DOCKERHUB_REPO : kovidms/pms-transactional
  IMAGE_TAG : latest

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code from Git repository
        uses: actions/checkout@v4
        
      - name: Debug workspace
        run: |
              pwd
              ls
      
      - name: Setup Docker build
        uses: docker/setup-buildx-action@v3
      
      - name: Build Docker image
        run: |
            docker build --progress=plain --no-cache -t $DOCKERHUB_REPO:$IMAGE_TAG .

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username:${{ secrets.DOCKERHUB_USER }}
          password:${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Push to DockerHub
        run: |
            docker push $DOCKERHUB_REPO:$IMAGE_TAG